### ISSUE TITLE
Server sometimes throws "Http: connection closed before message completed"

### ISSUE THREAD

**Issue by eibens** [eibens/edcb#31]
Error:

~~~txt
error: Uncaught (in promise) Http: connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:ext/http/01_http.js:202:27)
~~~

Here is some discussion: https://github.com/denoland/deno/issues/11595

**Comment by eibens** [comment]
The aforementioned discussion mentions that [one must correctly await promises](https://github.com/denoland/deno/issues/11595#issuecomment-899405780). Testing with using `await event.respondWith` seems promising.

**Comment by eibens** [comment]
Still occurs:

~~~
error: Uncaught (in promise) Http: connection closed before message completed
          await event.respondWith(response);
          ^
    at async Object.respondWith (deno:ext/http/01_http.js:202:27)
    at async https://deno.land/x/edcb@v1.0.0-alpha.2/utils/actions/listen.ts:29:11
~~~
